### ISSUE TITLE
可以把aria2缝进去吗

### ISSUE THREAD

**Issue by VOfficial404** [wy580477/Alist-on-Choreo#1]

**Comment by wy580477** [comment]
能缝，但是没啥意义。 只有挂载在内存里的 /tmp 目录可以写入，放不下啥大文件。

而且，我的账号已被 lock 了。( º﹃º )

**Comment by caiasi** [comment]
好像是要封账号，现在再搭隧道也不行了

**Comment by wy580477** [comment]
想想了，不搞了，仓库 archive 。

这个 Choreo 是提供 api 服务的， 拿来跑 web 应用肯定资源消耗模式差异很大，容易被风控。
